### PR TITLE
Variable Browser: Fix Callstack ListView

### PR DESCRIPTION
**Pull request by holycrepe**
This implements the following fixes:
1. Populate ListView
2. Use Correct Filename for Callstack
3. Jump to Code after Selecting a Frame from Callstack ListView

### CODE REVIEW

**Comment by holycrepe** [comment]
If you plan on merging these changes, I can rebase on the current master & fix merge conflicts

**Comment by maestrith** [comment]
I'm really bad at Github... I will do my best to see if I can find your edits and fix it :)

**Comment by holycrepe** [comment]
So it looks like you have some duplicate files due to case sensitivity:
1. ``README.md`` and ``Readme.md``
2. ``lib\Commands.xml`` and ``lib\commands.xml``

I'll submit another PR to fix that issue.  Once that is merged and I rebase this PR, you should be able to merge this PR without any conflicts

**Comment by maestrith** [comment]
Thank you! Do you use Skype, Discord, or Hangouts?  I am maestrith@gmail.com or maestrith on all of them.  I'd love to chat if you want to.

**Comment by holycrepe** [comment]
Please don't hesitate to give me a nudge if I fail to follow up!

**Comment by maestrith** [comment]
lol ok.

**Comment by maestrith** [comment]
so it was just the Display() function right?

**Comment by holycrepe** [comment]
I believe so... The changes affect the Subroutine that is called when the ListView is clicked.

**Comment by holycrepe** [comment]
FYI, When getting the filename for the current stackframe, I just cleaned up the filename instead of trying to validate it the same way you do elsewhere in the code. So there are some issues, ie nested library includes, as such:

```#Include <LibrarySubfolder\Module>```

I'll look into it further next week and open up new issues as needed

**Comment by maestrith** [comment]
thank you for taking the time to do that.  I really look forward to chatting.

**Pull request merged**
